<?php

/**
 * @file
 * Logs IP and timestamp of visiters to this site.
 */

/**
 * Implements hook_boot().
 */
function indicia_logger_boot() {
  // Capture current timestamp.
  $timestamp = REQUEST_TIME;
  // Convert unix timestamp to MySQL timestamp.
  $mysql_timestamp = date("Y-m-d H:i:s", $timestamp);
  // Capture visitors IP address.
  $user_ip = ip_address();
  // Store data in database.
  db_insert('indicia_logger')
    ->fields(array(
      'timestamp' => $mysql_timestamp,
      'user_ip' => $user_ip,
    ))
    ->execute();
}

/**
 * Implements hook_block_info().
 */
function indicia_logger_block_info() {
  $blocks = array();
  $blocks['indicia_logger'] = array(
    'info' => t('Indicia logger'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function indicia_logger_block_view($delta = 'indicia_logger') {
  // Create empty arrays.
  $variables = [];
  $block = [];
  // Set site name for template.
  $variables['site_name'] = variable_get('site_name');
  // Load data from db.
  $results = db_query('select * from {indicia_logger}');
  foreach ($results as $result) {
    $variables['logs'][] = [
      'timestamp' => $result->timestamp,
      'user_ip' => $result->user_ip
    ];
  }
  // Get template path.
  $template = drupal_get_path('module', 'indicia_logger') . '/theme/indicia_logger.tpl.php';
  $block['content'] = theme_render_template($template, $variables);
  return $block;
}